### ISSUE TITLE
"Contributions" column is weird

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/grambank#15]
What's going on with the "Contributions" column here:  https://grambank.clld.org/contributors -- these details are better seen on per-contributor pages e.g. https://grambank.clld.org/contributors/RHE, so can we remove these oddities.

**Comment by xrotwang** [comment]
Contributors should only be listed with the number of languages they contributed to. See https://github.com/glottobank/Grambank/issues/228#issuecomment-587380696

**Comment by HedvigS** [comment]
The languages are still wrongly summed.

**Comment by xrotwang** [comment]
@HedvigS the issue isn't closed yet.

**Comment by HedvigS** [comment]
Sorry, I just noticed this as some of the coders were asking about it and it reminded me of this thread. Thanks for doing this.
