### ISSUE TITLE
Brown and orange is super ugly.

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/grambank#17]

**Comment by xrotwang** [comment]
I was trying to derive a color scheme from this: https://glottobank.org/images/glottobank_all.jpg
Other proposals welcome.

**Comment by xrotwang** [comment]
@SimonGreenhill so what are we doing about this? I don't have any alternative proposals. Do you?

**Comment by SimonGreenhill** [comment]
(closed, will open specific issues if and when they arise)
