### ISSUE TITLE
mojibake on website

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/grambank#18]
"""
/lÃª/ 'the.m' and /sÃª/ 'the.f' function mostly like definite articles: /aba omba/ 'a big pig', /aba lÃª omba/ 'the big pig' or 'the pig which is big' or 'The pig is big.' /ne-sn-i-dÃ® aba lÃª led/ 'Give me this pig.' My only hesitation is that /lÃª/ and /sÃª/ cannot be phrase final--they always introduce other elements--so they might be better treated as relatives.
"""

See value for Anem (anem1249)  here: https://grambank.clld.org/parameters/GB020#2/17.3/152.1

**Comment by xrotwang** [comment]
This will hopefully change. I'm in the process of recreating db and web app.

**Comment by SimonGreenhill** [comment]
Yeah, looks like it's still in the raw data: https://github.com/glottobank/Grambank/blob/master/original_sheets/MD-GR-RSI_anem1249.tsv#L21

**Comment by SimonGreenhill** [comment]
and it's in some other sheets too e.g. original_sheets/JLA_minn1241.tsv

**Comment by xrotwang** [comment]
Hm. I remember cleaning up a couple of these. But it's difficult to detect if it can be read as valid UTF-8. I'll try to come up with a list of problematic "graphemes".

**Comment by SimonGreenhill** [comment]
yeah, it's a pain in the arse. I've used [this](https://github.com/LuminosoInsight/python-ftfy) before, but it's a little too enthusiastic. It might be useful to flag problems though (i.e. `if text != fit_text(text): print("ERROR!", text)`)

**Comment by SimonGreenhill** [comment]
I bet 90% of these are smart quotes...

**Comment by xrotwang** [comment]
Another problem is that these things mostly show up in the feature descriptions which are copied into the sheets - and **not** in comments. We don't care about the former, but we do about the latter. So I'll inspect comments in the cldf data first, I guess.

**Comment by xrotwang** [comment]
[`ftfy.fix_encoding`](https://ftfy.readthedocs.io/en/latest/#ftfy.fix_encoding) seems more conservative and only fixes mojibake. I found 376 such cases and in all of these the substitutions by `ftfy` seemed reasonable. I think we should run this cleanup on the `original_sheets`, though - even if we have to repeat this periodically. @SimonGreenhill  Agree?

**Comment by SimonGreenhill** [comment]
sounds good!

**Comment by xrotwang** [comment]
AFAIKT all these changes https://github.com/glottobank/grambank-cldf/pull/27/files#diff-6ee50492338999130996ae0257054107 seem ok.

**Comment by HedvigS** [comment]
Are most of these from JLA? Do we need to ask them any questions regarding their character encoding setup in their machine and spreadsheet programs or is this solvable without them?

**Comment by xrotwang** [comment]
See https://github.com/glottobank/grambank-cldf/pull/27/files#diff-6ee50492338999130996ae0257054107 
I think this is solvable without feedback from coders.

**Comment by HedvigS** [comment]
@xrotwang Okay, thanks. Then I shan't involve JLA.
