### ISSUE TITLE
detail pages linked from `family` return JSON

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/grambank#19]
go here https://grambank.clld.org/familys and select a family. You are redirected to a JSON endpoint: https://grambank.clld.org/familys/utoa1244

Perhaps a better location is https://grambank.clld.org/languages with the family filter set correctly?

**Comment by SimonGreenhill** [comment]
it would be quite nice to have a view for /languages/<family_id>/ which just shows the data points for `family_id`.

**Comment by xrotwang** [comment]
You mean a values table aggregating datapoints for all languages in the family? Is that actually a useful? What would you expect to see there? If you think the map view would be useful, I'd rather propose we code feature values as icon shapes and family as color - this would provide a bit of classification info in all feature maps.

**Comment by SimonGreenhill** [comment]
hmm, ok. I can see that people will want to drill down into the family level e.g. what do you have for UtoAztecan? 

What about a view that solves #12 e.g. two panels -- one map and one features-on-a-tree? I guarantee that this would get screenshotted and included in a million talks :)

**Comment by xrotwang** [comment]
Ah, ok. I see. So rather than selecting a family tree on a features'
details page, we'd have a feature selection on the family details page?

Simon J Greenhill <notifications@github.com> schrieb am Di., 29. Sep. 2020,
21:05:

**Comment by xrotwang** [comment]
So https://grambank.clld.org/familys/utoa1244 has a map of the varieties and the table of coded values for all features (so far). Will have to think about where to put the tree with values for a single feature.

**Comment by xrotwang** [comment]
Maybe the family details page will need a feature selection box and accept a URL parameter `parameter=GB020`. That would still be transparent and linkable enough, I'd think.

**Comment by SimonGreenhill** [comment]
cool! thanks. I think the idea to have ?parameter=xxx will be very helpful.

**Comment by xrotwang** [comment]
So here's family page with tree and selectable features: https://grambank.clld.org/familys/algi1248?feature=GB022#tree-container

**Comment by SimonGreenhill** [comment]
this is awesome, thanks  @xrotwang ! one nitpick -- the 0's are quite hard to see, is it easy to up the contrast (reduce alpha?) or change the color?

**Comment by xrotwang** [comment]
Ah, yes. For maps with less dots the opacity doesn't make much sense.

**Comment by xrotwang** [comment]
Changing the colors is easy, too. Proposals? [PRs](https://github.com/clld/grambank/blob/15dd7e1f352ec9964307212ce2c0911011939dae/grambank/scripts/util.py#L56-L59)?

**Comment by SimonGreenhill** [comment]
sorry for bikeshedding, but what about https://colorbrewer2.org/#type=qualitative&scheme=Set1&n=4 or https://personal.sron.nl/~pault/ (actually fig 3 in the last link looks good, and is color blind friendly, so that would be nice). 

Can we make:
? = gray cbbbbbb  (is ? mapped? if not then don't worry)
0 = blue c0077bb
1 = red   ccc3311
2 = teal  c009988
3 = orange cee7733

**Comment by xrotwang** [comment]
https://grambank.clld.org/parameters/GB024#map-container

**Comment by SimonGreenhill** [comment]
looks good!
