### ISSUE TITLE
"?" is not a valid CLDF ID

### ISSUE THREAD

**Issue by Anaphory** [clld/grambank#2]
Grambank's ID for “Not Known”, `?`, is not a valid CLDF identifier. On one hand, this is okay, I guess, because “Not Known” is also not a real value that other CLLDs should link to, but could it not lead to URL issues to use it anyway? (Given that domain elements are not listed on their own, I have not seen it appear in any URL, I'm just wondering, also in the context of Best Practice.)

**Comment by xrotwang** [comment]
clld apps which employ `DomainElement` objects typically use the numeric values of these objects as part of their IDs.
