### ISSUE TITLE
filtering on languages page doesn't update map

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/grambank#20]
This might be annoying to fix but it would be nice if filtering  https://grambank.clld.org/languages updated the map too

**Comment by xrotwang** [comment]
Yes, this comes up regularly :)
But doing this would mean we'd have to retrieve **all** results of a filtered query at once to update the map - as opposed to only retrieving the first batch to fill the table. So this requirement is fundamentally at odds with the idea of paged filter results in the table.

No offense - but wontfix :)

**Comment by xrotwang** [comment]
Apps with such a functionality typically keep **all** relevant data in the browser and do the filtering client side, in javascript. But `clld` wants to scale to large amounts of rows in all tables - thus has "paged" results as core design principle.

And I think that this disconnect between map and table filtering is transparent enough - or the other way round: full synchronisation would be hard to get, e.g. filtering the table to what's in the viewport of the map ...

**Comment by SimonGreenhill** [comment]
yeah, I thought that would be the case :)
