### ISSUE TITLE
Combining features

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#23]
In past versions of the website there was a way of combining features and see the distributions of combinations. This functionality is not there anymore. Can you refresh me @xrotwang to why that is? I've got people asking if it can be brought back, and I'm not sure how involved that is.

**Comment by HedvigS** [comment]
It seems it's still possible through URL manipulation
[https://grambank.clld.org/combinations/GB118_GB150#2/17.1/151.9](https://grambank.clld.org/combinations/GB118_GB150#2/17.1/151.9)

**Comment by xrotwang** [comment]
We haven't come up with a final list of functionalities for the website yet, I think. We can use issues here as proposed functionalities - maybe tagged suitably.

**Comment by HedvigS** [comment]
Sure thing! I know Simon wanted to add trees (#12 ) and I'm sure people have other ideas as well.

For now, I just wanted to keep it small and ask if this thing that used to be there can be there again :)

**Comment by HedvigS** [comment]
So, do we want a GUI for this?

**Comment by HedvigS** [comment]
Got a request from the CoOL gang to have this. What do you think @xrotwang

**Comment by xrotwang** [comment]
issue is already open. so all good :)

**Comment by HedvigS** [comment]
Great, thanks Robert!

**Comment by HedvigS** [comment]
The Grambank manuscript is advancing in the submission system, we may be looking at a publication soon. Is it possible to get a button with rounded corners for this functionality within 2 months?

**Comment by xrotwang** [comment]
I don't understand what "button with rounded" means, but maybe @johenglisch can look into this.

**Comment by HedvigS** [comment]
Okay.

It would be nice if the funcationality on the website whereby you could click a button that said "combine features" and search for features and get to the combined map is brought back. "button with rounded corners" is my shorthand for GUI interface function for the underlying tool that already exists.

**Comment by HedvigS** [comment]
example from dplace website
![Screenshot 2023-03-01 at 12 54 27](https://user-images.githubusercontent.com/5327845/222132469-4701a268-187d-478d-a529-d58034abf1ee.png)

**Comment by johenglisch** [comment]
I'll take a look at it.

So, basically there's functionality in the webapp that's *there* but not exposed in the ui?  That should be simple (in theory).

Where is this form supposed to go?  From the wording it looks like it's from the page of a particular GB feature?

**Comment by HedvigS** [comment]
@johenglisch  yes exactly. we patrons use the URL and modify that to get the functionality, but it would be great if it's in the UI directly.
It can go where-ever is easiest, I'm not too fussed. I think other CLLD webapps have it, so whereever they have it I'm sure is good :)
