### ISSUE TITLE
non feature wiki content

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#24]
In the Grambank wiki, we have other content besides specific feature descriptions that are relevant for users and people who are curious about the database. [Jakob's made a great starting page with shows the content of the wiki nicely](https://github.com/grambank/grambank/wiki).

Can there be a tab or something somewhere on the clld website along the lies of "For more information, including contributing  data, see our wiki":

**Comment by HedvigS** [comment]
I can't assign anyone to this issue. Not sure where to go from here.

**Comment by xrotwang** [comment]
Stuff that can only be done by me doesn't need to be assigned.

**Comment by HedvigS** [comment]
Ok.
