### ISSUE TITLE
adding "People" tab

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#27]
Russell has requested that we add a "People" tab to grambank.clldf.org. It should be similar to the tab at glottobank.org, but with sections. The sections should be:

Project leaders
Russell, Quentin, Simon

Project coordinators
Hedvig, Harald

Database manager
Robert Forkel

Patrons and node leaders
Jeremy, Jay, Hannah, Hannah, Jacob, Hedvig, Tobias, Alena

Coders
Anyone who is a contributor and has an image and blurb at glottobank.org

Senior advisors
Nick, Steve L, Martin, Michael Dunn

**Comment by xrotwang** [comment]
Btw,: Does the paper link to the website? I.e. does the website need to be up-to-date at the time of submission of the paper? And if so - when is that?

**Comment by HedvigS** [comment]
Sure. The paper links to grambank.clld.org and zeonodo. It's in a section you wrote in the sup materials.
I don't know when the publication will be, but I estimate within a few months.

**Comment by HedvigS** [comment]
Russell also gave me notes on updates to glottobank.org. Where should I leave them?

**Comment by xrotwang** [comment]
Send the notes by mail, please. And my question was about the website status at paper **submission** not publication.

**Comment by HedvigS** [comment]
Will do.

Okay, sorry. I have no idea about that but I would guess "in several months".

**Comment by xrotwang** [comment]
@HedvigS should this page include text blurbs and images? And if so, should they just be grabbed from glottobank.org?

**Comment by HedvigS** [comment]
Yes, text and images. Contributors who have not sent in a text or blurb should just be listed with their names.
