### ISSUE TITLE
Add column for datapoints

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#3]
On the website, can there please be a column for number of datapoints per lg?
Here.
http://grambank.clld.org/languages

**Comment by d97hah** [comment]
Implemented, Robert can push online whenever convenient for him. all the
best, H

2016-09-08 12:27 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by xrotwang** [comment]
will probably not get to it until after poznan

**Comment by HedvigS** [comment]
Thanks for making that change. New idea.. could there be two datapoints columns? One for how many features are filled out for that language with “?” and without “?”? (This is probably interesting for many more CLLD-sites)

**Comment by HedvigS** [comment]
Nevermind
