### ISSUE TITLE
Load and display values.csv Source_comment

### ISSUE THREAD

**Issue by xrotwang** [clld/grambank#31]
"p.c." source info currently isn't displayed in the Grambank app, but should be.

**Comment by HedvigS** [comment]
Yes, exactly. Everything that passes the pygrambank sourcelookup text but isn't mapped to a bibtex-record should be visible. Things that don't qualify, I can't imagine exactly what they'd be but non-"p.c." and non-bibtex entries should invalidate the datapoint.
