### ISSUE TITLE
forms for incoming suggestions

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#33]
Could we have a contact form on the website and a [github issue form ](https://beyondco.de/blog/github-issue-forms) (for those who have github accounts) where we direct people who have comments about changes in Grambank coding?

The form on the website could maybe somehow genreate a github issue as well, that'd be marvelous. Even if it didn't, it'd be great to have some kind of buffer that imposes some structure so that we don't just get bombarded with emails to grambank@eva.mpg.de

I know we've discussed this before and that it might not get as bad so that this is needed.. but. I would really apprecaite if we could implement even the simplest of forms on the website. Just to direct people and structure the influx. I already get emails from department members about changes here and there, and if I know linguists right... I'm going to get a lot more as soon as the release is out :)

**Comment by xrotwang** [comment]
We can add [mailto links with a body template](https://css-tricks.com/snippets/html/mailto-links/#adding-body-text). That's what we do with Glottolog, e.g. when you click the button with the bell [here](https://glottolog.org/resource/reference/id/585487).

I'd assume the issue forms would go into `grambank/grambank`, right? You should have sufficient permissions to add them there. Maybe that's also a good starting point for me to figure out which mailto links you'd want and where.

**Comment by HedvigS** [comment]
Mailto with a template sounds good to me.

Yes, they'd go to the public repos where we're storing the data (not where the code for the ms will be). Okay, I'll tinker with github issue forms!

**Comment by HedvigS** [comment]
I've made two github issue forms now, I can fidget with them more but I think i'm essentially done. If there could be those two, and an "other" for email forms that'd be great
