### ISSUE TITLE
features col under languages and dialect should not count ?

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#36]
I think we should not count missing or ? for the summary stat in the col "Features" in the table under the languages and dialects tab.

**Comment by xrotwang** [comment]
Why - doesn't `?` mean the feature was evaluated against the available description, i.e. something else than "dunno"? And if we don't count it here, then it should count nowhere, right, e.g. in the "languages and dialects" column at https://grambank.clld.org/parameters?

**Comment by HedvigS** [comment]
We've opted for two different ways of counting missing data, one for how to evaluate the descriptive level and one to evaluate the data we can use for analysis. For the first one, ? vs NULL matters but for the second one this is not the case. I think that most users would expect us to report the second case here.

**Comment by HedvigS** [comment]
Yes, it should be symmetrical at the features tab.

**Comment by xrotwang** [comment]
And as "Datapoints" count on the landing page?

**Comment by HedvigS** [comment]
Good question. For the languages and dialects-table and the parameters-table I think it'd be too confusing to have more than on col for datapoints, but on the landing page maybe we can afford two rows? One

"Data-points (excl ?)"
"Data-points (incl ?)"
