### ISSUE TITLE
All contributors should be listed on the language page

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#37]
for waor1240 JR is missing from the contributors panel on the clld website page for the language
https://grambank.clld.org/languages/waor1240

**Comment by HedvigS** [comment]
Also similar for the "Contributor" column on the language tab. Thank you!

**Comment by HedvigS** [comment]
Similar case for when it comes to the summary stats per person on[ the contributors tab](https://grambank.clld.org/contributors#coder) which would be best turned into number of datapoints, including content as "Contributed_datapoint".

**Comment by xrotwang** [comment]
See https://grambank.clld.org/languages/waor1240

**Comment by HedvigS** [comment]
Excellent, many thanks. And I see that the summary stats on the people tab have also been updated, super!
