### ISSUE TITLE
add link to wiki contributing article on website tab contact

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#38]
It'd be great if there could be a link[ to this page](https://github.com/grambank/grambank/wiki/Contribute)[ here.](https://grambank.clld.org/contact) The tab could also be changed to "Contact/contribute" to make it extra clear.

**Comment by xrotwang** [comment]
Changing the link name to "Contact/contribute" would be somewhat complicated. Is that essential?

**Comment by HedvigS** [comment]
No I guess not, the way it says now with the sub heading "Contribute" should be ok. Thanks!
