### ISSUE TITLE
Combination of features in the webb app

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#4]
Can the web apps for Grambank and NTS please have the functionality of combining features, like WALS and SAILS does?

Thanks Robert!

**Comment by xrotwang** [comment]
Any good reasons for this? They aren't even public and grambank in particular is just intended to be a browsable catalog of what's there, not an analysis tool, as far as I understood.

**Comment by HedvigS** [comment]
It's a very useful feature when browsing the catalogue since it geographically visualizes things quickly. I thought since it's on the other sites, it'd be a relatively easy implementation instead of something new.

I was showing something to a colleague and that's when I noticed it wasn't there.

**Comment by xrotwang** [comment]
It doesn't cause trouble, but it's not just flipping a switch either. Each line of code comes at a cost, which ideally has to be justified. WALS has this feature because of legacy and because it seems to be used for teaching quite a bit. SAILS got it because I was more open-handed by then :)

**Comment by HedvigS** [comment]
Ok. Well, it's not crucial, but it is useful for browsing catalogues and one of the features people like about those sites. It's up to you, whoever decides over your time and/or @d97hah wether or not to implement it. I just thought I'd bring it up, since it's not there and appreciated elsewhere.

You're right, these sites are not analysis tools and I appreciate that you want to encourage more users of these catalogues to interact with the dataset with proper analysis tools.

**Comment by d97hah** [comment]
I don't really think it's worth, it's just you who used NTS and the data is
almost the same as in GB. Btw how are your Python skills coming on, maybe
one day you can do this (or other things like it) on your own too?

2017-07-06 17:15 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Hi @d97hah ! Perhaps there's been a misunderstanding, I don't want to have the ability to compare NTS to GB, but to compare GB to GB. You know like how you have it on the SAILS website, and WALS?

I can do this in R, working on it now :). I brought this up as a CLLD-app thing because it's useful for web app users when browsing.

**Comment by d97hah** [comment]
Oh sorry, I read it as referring to NTS only. In GB you can already get
that information, e.g.
http://grambank.clld.org/combinations/GB130_GB131#2/18.2/144.7

2017-07-07 9:59 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Aaaah ^^!!! Ok. It was just not in the place I was looking for it! This is much better, excellent! Thanks @d97hah

**Comment by HedvigS** [comment]
Related to this, @d97hah have you run any analysis on the current data set for the quirk-based distances as well?

**Comment by d97hah** [comment]
No

2017-07-17 5:18 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
@d97hah Ok. Is it alright if I ask some more questions about these dependencies and the analysis here? I want to understand all of this better.

**Comment by HedvigS** [comment]
@d97hah Ok

**Comment by d97hah** [comment]
Ask all you like here or wherever!

2017-07-19 4:23 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Thanks @d97hah
 
I just realised that Siva can't read this thread, and that that might be relevant. I'll move.
