### ISSUE TITLE
reduce size of images on contributors page

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/grambank#43]
Some are large and take a long time to load

**Comment by johenglisch** [comment]
Hm, from what I can tell the photos aren't actually stored in the grambank app but hotlinked to https://glottobank.org/people.html (or rather to `https://glottobank.org/photos/*`).

I guess we could just upload downscaled versions of the photos [over there](https://github.com/glottobank/glottobank.github.io/tree/master/photos) and fix the problem on both site at once.

Or we could add smaller pictures to this repo and live with the duplication.

**Comment by xrotwang** [comment]
Downscale at https://github.com/glottobank/glottobank.github.io/tree/master/photos I'd say. Can do that later today.

**Comment by xrotwang** [comment]
I downscaled all photos which had a size >1MB.
