### ISSUE TITLE
open up to branching at this repos

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#46]
I know the cldf way is to encourage forks instead of branches, but for this repos can we please make it possible for people to branch instead? we can protect main branch, no worries. 
I find that working with forks instead of branches complicates my workflow. I know we've talked about it [before](https://github.com/glottolog/glottolog/issues/812) with glottolog/glottolog and I've given up there, but if possible I'd really appreciate if we can do it here.

**Comment by xrotwang** [comment]
I don't really understand. CLDF doesn't have anything to do with branches or forks. And this repository - the code of the grambank clld app - doesn't have much to do with CLDF. Do you want to contribute to the app code?

**Comment by xrotwang** [comment]
Ah, I see #45 . If @johenglisch is fine with it, you can get write access here. It's always a bit tricky, if someone who can't actually run the web app edits the code. In the case of templates, that can work out, though. So I'll leave that to @johenglisch - who is most probably the one to deploy it to the server.

**Comment by HedvigS** [comment]
Yes, #45 for example.

I don't know where the decision is made, but it seems like several CLDF-reposes opt for fork-based edits instead of branch-based, like D-PLACE/dplace-data and glottolog/glottolog. I understand that it's not a CLDF-rule per se, but I wasn't sure what else to name it :). It makes it less likely for me to engage, and I'd like to be able to do things at least where grambank is concerend. Keep main branch protected, no worries. Just, let me branch and be able to make PRs :)

**Comment by xrotwang** [comment]
The decision about a contribution workflow - and consequently about who to grant write access to a repository is typically made by the maintainers. For datasets like for software packages that would be the people who can make releases, for a piece of software that runs on a server it's the people deploying the code - because they are typically the ones dealing with the consequences. So, over to @johenglisch

**Comment by johenglisch** [comment]
@HedvigS If I did everything right you should have an invite for write access.  I also enabled branch protection for `master` (mainly because I've never done it before -- but also because I have definitely pushed to master by accident in the past (<_<)" ).

**Comment by HedvigS** [comment]
Love it. 
Main branch protected and inclusive branch-rights is my favourite set up :)
