### ISSUE TITLE
CSV sheet per language download improvement

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#5]
The formatting of the csv sheets that get generated when you click download per language needs some improvement. 

Is it possible to also have two separate columns for language and feature number, i.e. glottoid and grambank-iD? As it is now they're only found merged in one column.

Many of the other columns that are generated have names that are not directly transparent, for example "domainelement_pk". I tried searching the CLDF repos for explanations, but found nothing.

I would suggest simplifying the csv-sheets per language and per feature to just the columns that are on the web-app, i.e. for languages:

 "Feature ID", "feature question", "value", "source", "comment" and in addition"ID" which is GlottoID + feature ID.

for features:

"Language name", "Glottoid", "Contributor", "value", "source", "comment + ID (see above).

Furthermore, we need to make sure that users know the difference between "contributor" and "coder" here. The "contributor" label could even be changed to "designer" instead and coder could be added as a separate column.

Right now btw, for the web app display of each feature it says "ISO 639-3" for the "GlottoID/Glottocode" column. That should be changed.

**Comment by HedvigS** [comment]
I can't seem to "assign" @xrotwang  and @d97hah  so I'm mentioning you now.

**Comment by xrotwang** [comment]
Honestly, I'd rather do away with the CSV downloads on each table. There are several browser plugins out there which allow you to scrape each table on a website as CSV, with the additional benefit of getting a table that contains exactly what you saw. I'd rather emphasize the CLDF download as **the** way to access the Grambank data.

**Comment by HedvigS** [comment]
Fine, that's an understandable position. However if they do remain, they should be made sensible.

What does the other CLLDers Haspelmath and @d97hah prefer? I take it this is relevant on basically all sites that will have/has CLDF

**Comment by xrotwang** [comment]
I don't think this is a question of preference, but one of feasibility: I've been fighting the "make it accessible to non-computer savvy people" battle for quite some time now. My experience is that the CSV download doesn't help. The group of people that cannot access data in a format like CLDF also largely struggles with CSV basics like re-ordering or renaming columns, sorting, etc.

**Comment by HedvigS** [comment]
Fair enough.

Either way, the Grambank site when it is released should either have this function and have it labeled well, or not have it at all. And the columns with either ISO 639-3 or Glottocodes should have the right column names.

Thanks Robert.

**Comment by d97hah** [comment]
Ok I've taken care of the name of the ISO 639-3 column for next update.
And I've put it on my todo-list to make the CSV download have intelligible
column headers (I do think this is a nice service to our non-computer savvy
friends)

2017-10-10 13:22 GMT+02:00 Hedvig Skirgård <notifications@github.com>:
