### ISSUE TITLE
Feature suggestion: link language pages to glottolog

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#59]
Claire Bowern suggest we link language pages to glottolog 

https://github.com/grambank/grambank/issues/38

**Comment by xrotwang** [comment]
@johenglisch should be simple (I think), see https://github.com/clld/lexibank/blob/74b1ad7f1a8fe660722180be2abfe30829cf10a2/lexibank/templates/language/detail_html.mako#L38
