### ISSUE TITLE
Request to update the "How to cite Grambank" section on the website

### ISSUE THREAD

**Issue by OlenaShcherbakova** [clld/grambank#60]
The current version (including the doi) is outdated at [https://grambank.clld.org/](url).

**Comment by xrotwang** [comment]
Do you mean the paper citation? The DOI added here (https://github.com/clld/grambank/commit/0ea17f18d39a39b5a1cbf9d4f94a66bae32f5407 ) does look invalid - there's typically a prefix and the identifier part, separated by `/`.

**Comment by xrotwang** [comment]
Ah, yes, should be `10.1126/sciadv.adg6175`.

**Comment by HedvigS** [comment]
My mistake, I don't know how that happened.
