### ISSUE TITLE
grambank logo instead of glottobank

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#63]
Martin thinks that the logo on the home page should be the grambank logo, not the glottobank logo. I.e.
![single_GramBank (1)](https://github.com/clld/grambank/assets/5327845/16711c5c-c05e-4c13-b8e3-8009b902c56c)

**Comment by xrotwang** [comment]
Hm. We have the "individual bank" logos on top left for https://grambank.clld.org as well as https://lexibank.clld.org and we do have "individual bank" color coding. So I'd say the overall Glottobank brand needs to be present somewhere (and the current solution looks suitable for this to me).

**Comment by xrotwang** [comment]
We'll talk about what to do with glottbank.org at the next programmers meeting. If we decide to de-emphasize the Glottobank brand because it's too much effort to maintain, then I guess we'll follow @haspelmath 's proposal here.

**Comment by HedvigS** [comment]
@xrotwang can we close this issue? I suspect that Martin's proposal was voted down at the programmer's meeting.
