### ISSUE TITLE
contributors on language page not taking "contributed_datapoints" into account?

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#71]
Why does SR (Sydney Rey) not appear as a contributor for the language page for macu1260?

**Comment by xrotwang** [comment]
```$ csvgrep -c Language_ID -m macu1260 cldf/values.csv | csvcut -c Coders | sort | uniq
Coders
HunterGatherer
```

**Comment by johenglisch** [comment]
I had a look as well:  The coder is in the wrong column (`Feature Domain` instead of `Contributed_Datapoints`).

https://github.com/glottobank/Grambank/blob/master/original_sheets/CB-PE-AS_macu1260.tsv

**Comment by HedvigS** [comment]
> I had a look as well: The coder is in the wrong column (`Feature Domain` instead of `Contributed_Datapoints`).
> 
> https://github.com/glottobank/Grambank/blob/master/original_sheets/CB-PE-AS_macu1260.tsv

Ah, there we go. Okay. Hm, I wonder if this has happened more times. Thank you for spotting @johenglisch !
