### ISSUE TITLE
value count table on feature pages

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#72]
Can we please have a feature value count table added to the feature pages? For example, similar to WALS maps pages.

**Comment by johenglisch** [comment]
![wals-feature-value-count-table](https://github.com/clld/grambank/assets/1862047/038b50d8-0b71-4c37-b07f-7bd61213e57f)

**Comment by HedvigS** [comment]
> ![wals-feature-value-count-table](https://user-images.githubusercontent.com/1862047/285187702-038b50d8-0b71-4c37-b07f-7bd61213e57f.png)

Stimmt.
