### ISSUE TITLE
Contributors with 0 datapoints

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#74]
Why are people who contributed 0 data-points to Grambank v1.0 listed [here](https://grambank.clld.org/contributors) and if they absolutely need to be, could the statement underneath their name please up changed so it doesn't say `Contributed datapoints for languages and dialects`, which appears to be the same strings as the others but with missing digits.

**Comment by xrotwang** [comment]
I guess that's people listed as Coders in https://github.com/glottobank/Grambank/blob/v1.0.4/CONTRIBUTORS.md

**Comment by xrotwang** [comment]
@johenglisch could you change the template such that it doesn't include the "Contributed datapoints ..." bit for the ones with 0 datapoints?

**Comment by HedvigS** [comment]
> I guess that's people listed as Coders in https://github.com/glottobank/Grambank/blob/v1.0.4/CONTRIBUTORS.md

Yep, I think that's it.

**Comment by HedvigS** [comment]
> @johenglisch could you change the template such that it doesn't include the "Contributed datapoints ..." bit for the ones with 0 datapoints?

another alternative is that people with 0 data-points don't show up in the coders section.

**Comment by xrotwang** [comment]
> another alternative is that people with 0 data-points don't show up in the coders section.

Not really, often Coder is the only role they have.

**Comment by HedvigS** [comment]
Genau. I don't understand why coders with 0 datapoints should appear, seems
confusing to me.

**Comment by xrotwang** [comment]
As far as I remember, everyone on the paper should be on the web app, too. That's why we just stick with what's in CONTRIBUTORS.md.

**Comment by HedvigS** [comment]
> As far as I remember, everyone on the paper should be on the web app, too. That's why we just stick with what's in CONTRIBUTORS.md.

It is not the case that everyone on CONTRIBUTORS.md is an author on the release paper. There were cut-off limits on number of data-points. CONTRIBUTORS.md is a list of everyone who is on the release paper (minus one) and also coders that have joined the project since the rendering of Grambank version 1.0 and other coders who did not make the cut-off.

**Comment by HedvigS** [comment]
RG gave me instructions for who should be on the data zenodo publication and who should be on the release paper. I used CONTRIBUTORS.md to keep track of the order of people's names and for pygrambank to check that the coder initials exists, but the full table is not the exact list of authors on the zenodo release OR the release paper. I know, a bit confusing.

**Comment by xrotwang** [comment]
But @johenglisch' fix is ok?

**Comment by HedvigS** [comment]
> But @johenglisch' fix is ok?

I appreciate the string fix. Personally, I would prefer that people with 0 data-points in the dataset underlying the clld-web app don't appear at all.
