### ISSUE TITLE
Odd behaviour of website reported by Comrie

### ISSUE THREAD

**Issue by HedvigS** [clld/grambank#82]
Bernard Comrie got in touch and let us know 

1) the data-point czec1258 GB193 shouldn't be `2`(I've dealt with that here: https://github.com/grambank/grambank/issues/67)

2) that he thinks that it's possible that data-point used to be `3` some weeks ago. For this I have no insight, as far as I know, the website app hasn't been updated for a long time now.

3) that when he clicks the coders name, `Kim K Salmon`, the list of languages doesn't include Czech.

4) that when he clicks on Czech, he gets two coders names `Aikaterina Koti` and `Kim K. Salmon`

Can you @johenglisch and/or @xrotwang please help me with 2:4?

Vielen dank.

**Comment by xrotwang** [comment]
Can confirm 4 - which is also the expected behaviour. Cannot confirm 3.

**Comment by johenglisch** [comment]
>he thinks that it's possible that data-point used to be 3 some weeks ago

I checked the CLDF data for Grambank v1.0.3 and czec1258 is set to 2 there as well, so unless something went horribly wrong it should have been like that the entire time.

Side note:  My knowledge of Czech is fairly limited but a `3` would look a bit sus, too.  I think I've only ever seen Adj–N ordering in Czech (`3` seems more like a Polish thing to me).  But anyway, that's for the Coder to decide.

>when he clicks the coders name, `Kim K Salmon`, the list of languages doesn't include Czech

It's there:

![ksa-attribution-for-czech](https://github.com/user-attachments/assets/294b41f5-6232-4ea2-95d4-270041696767)

Tough to be honest it looks a bit out-of-place down there in the table.  The Austronesian group is so large that table looks like it's sorted by language not by family – maybe that's where the confusion stems from?  Or maybe he was looking at a different table?

>when he clicks on Czech, he gets two coders names `Aikaterina Koti` and `Kim K. Salmon`

Can confirm as well.  As there should be:

    $ csvgrep -c Language_ID -m czec1258 cldf/values.csv \
        | csvcut -c Coders \
        | sed 1d | tr ';' '\n' \
        | sort -u
    KK
    KSA

**Comment by HedvigS** [comment]
> > he thinks that it's possible that data-point used to be 3 some weeks ago
> 
> I checked the CLDF data for Grambank v1.0.3 and czec1258 is set to 2 there as well, so unless something went horribly wrong it should have been like that the entire time.
> 
Yes, that's what it looked like to me too

> Side note: My knowledge of Czech is fairly limited but a `3` would look a bit sus, too. I think I've only ever seen Adj–N ordering in Czech (`3` seems more like a Polish thing to me). But anyway, that's for the Coder to decide.
> 
Fair ^^! We'll see what happens

> > when he clicks the coders name, `Kim K Salmon`, the list of languages doesn't include Czech
> 
> It's there:
> 
> ![ksa-attribution-for-czech](https://private-user-images.githubusercontent.com/1862047/383134478-294b41f5-6232-4ea2-95d4-270041696767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTI1MzYsIm5iZiI6MTczMDgxMjIzNiwicGF0aCI6Ii8xODYyMDQ3LzM4MzEzNDQ3OC0yOTRiNDFmNS02MjMyLTRlYTItOTVkNC0yNzAwNDE2OTY3NjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTMxMDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFmMGJjMzhiOTA4ZGNkMTgxYTZlMzA4YzNkYTRmYzQ5OTA5Yjg3NDQ1OGU5MWEyMGU3MjE4ZTczMDJlZGY1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.U7FoH7Z-ha-25slwmQgnOZXwnOcf3LbLOg__nPzPyds)
> 
> Tough to be honest it looks a bit out-of-place down there in the table. The Austronesian group is so large that table looks like it's sorted by language not by family – maybe that's where the confusion stems from? Or maybe he was looking at a different table?
> 

I don't know. I'm just glad it looks like the website is working.

> > when he clicks on Czech, he gets two coders names `Aikaterina Koti` and `Kim K. Salmon`
> 
> Can confirm as well. As there should be:
> 
> ```
> $ csvgrep -c Language_ID -m czec1258 cldf/values.csv \
>     | csvcut -c Coders \
>     | sed 1d | tr ';' '\n' \
>     | sort -u
> KK
> KSA
> ```

**Comment by HedvigS** [comment]
It looks like none of us can reproduce the problematic behaviour, so I think I'll close the issue.
